---

language: python
python:
  - 3.6
  - 3.8

before_install:
  - pip install poetry codecov coverage

install:
  - poetry install --no-root

script:
  - coverage run -m unittest discover -v -s remote_eink/tests

after_success:
  - coverage combine -a
  - coverage report
  - codecov
