---

openapi: 3.0.0
info:
  version: 0.0.1
  title: Image Display Service

paths:
  /display:
    get:
      summary: Get displays
      operationId: getDisplays
      responses:
        200:
          description: List of displays retrieved.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: ID of displays.

  /display/{displayId}:
    get:
      summary: Get a display
      operationId: getDisplayById
      parameters:
        - $ref: "#/components/parameters/displayId"
      responses:
        200:
          description: Display retrieved.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Display"
        404:
          description: Display not found.

  /display/{displayId}/image-transformer:
    get:
      operationId: getDisplayImageTransformers
      summary: Gets an list of image transformer IDs
      parameters:
        - $ref: "#/components/parameters/displayId"
      responses:
        200:
          description: List of image transformer IDs.
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/ResourceId"

  /display/{displayId}/image-transformer/{imageTransformerId}:
    get:
      summary: Gets details about a display image transformer
      operationId: getDisplayImageTransformer
      parameters:
        - $ref: "#/components/parameters/displayId"
        - $ref: "#/components/parameters/imageTransformerId"
      responses:
        200:
          description: Details about the image transformer.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageTransformer"

    put:
      summary: Updates the configuration of an image transformer
      operationId: putDisplayImageTransformer
      parameters:
        - $ref: "#/components/parameters/displayId"
        - $ref: "#/components/parameters/imageTransformerId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ImageTransformer"
      responses:
        200:
          description: Configuration updated.

  /display/{displayId}/current-image:
    get:
      summary: Get ID of the image currently being displayed
      operationId: getDisplayCurrentImage
      parameters:
        - $ref: "#/components/parameters/displayId"
      responses:
        200:
          description: ID of currently displayed image
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/ResourceId"
        404:
          description: No current image set.

    put:
      summary: Puts the image onto the display.
      operationId: putDisplayCurrentImage
      parameters:
        - $ref: "#/components/parameters/displayId"
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: "#/components/schemas/ResourceId"
      responses:
        200:
          description: Set device's sleep status as instructed.

    delete:
      summary: Clear display of the current image
      operationId: deleteDisplayCurrentImage
      parameters:
        - $ref: "#/components/parameters/displayId"
      responses:
        200:
          description: Image cleared from the display.

  /display/{displayId}/image:
    get:
      summary: Get IDs of images that can be displayed
      operationId: getDisplayImages
      parameters:
        - $ref: "#/components/parameters/displayId"
      responses:
        200:
          description: Image list retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ResourceId"

  /display/{displayId}/image/{imageId}:
    get:
      summary: Get data for an image that can be displayed
      operationId: getDisplayImageById
      parameters:
        - $ref: "#/components/parameters/displayId"
        - $ref: "#/components/parameters/imageId"
      responses:
        200:
          description: Image retrieved
          content:
            image/*:
              schema:
                format: binary
        404:
          description: Image not found.

    post:
      summary: Uploads an image onto the device
      operationId: postDisplayImage
      parameters:
        - $ref: "#/components/parameters/displayId"
        - $ref: "#/components/parameters/imageId"
      requestBody:
        content:
          image/*:
            schema:
              format: binary
      responses:
        201:
          description: Image created.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ResourceId"

    delete:
      summary: Delete an image from the device
      operationId: deleteDisplayImageById
      parameters:
        - $ref: "#/components/parameters/displayId"
        - $ref: "#/components/parameters/imageId"
      responses:
        200:
          description: Image deleted.

  /display/{displayId}/sleep:
    get:
      summary: Gets whether the device is sleeping
      operationId: getDisplaySleep
      parameters:
        - $ref: "#/components/parameters/displayId"
      responses:
        200:
          description: Sleep status
          content:
            application/json:
              schema:
                type: bool

    put:
      summary: Set the device sleep status
      operationId: putDisplaySleep
      parameters:
        - $ref: "#/components/parameters/displayId"
      requestBody:
        content:
          application/json:
            schema:
              type: boolean
      responses:
        200:
          description: Set device's sleep status as instructed.

components:
  parameters:
    displayId:
      name: displayId
      in: path
      required: true
      schema:
        type: string
      description: ID of the display.
    imageId:
      name: imageId
      in: path
      required: true
      schema:
        type: string
      description: ID of the image.
    imageTransformerId:
      name: imageTransformerId
      in: path
      required: true
      schema:
        type: string
      description: ID of the image transformer.

  schemas:
    ResourceId:
      type: object
      properties:
        id:
          type: string
          description: ID of the resource.

    ImageTransformer:
      type: object
      properties:
        id:
          type: string
          description: ID of the image transformer
        description:
          type: string
          description: Description of what the image transformer does
        active:
          type: boolean
          description: Whether the image transformer is active
        position:
          type: integer
          description: Position in image processing pipeline, where `1` is first.
        configuration:
          type: object
          description: Transformer configuration (transformer specific content)

    Display:
      type: object
      properties:
        id:
          type: string
        currentImage:
          $ref: "#/components/schemas/ResourceId"
        images:
          type: array
          items:
            $ref: "#/components/schemas/ResourceId"
        orientation:
          type: integer
        cycleImages:
          type: boolean
        cycleRandomly:
          type: boolean
        cycleAfterSeconds:
          type: integer
