[tool.poetry]
name = "remote_eink"
version = "1.0.0"
description = ""
license = "AGPLv3.0"
authors = [
    "Colin Nolan <cn580@alumni.york.ac.uk>"
]
readme = "README.md"
include = ["LICENSE", "openapi.yml"]
repository = ""
homepage = ""
keywords = []

[tool.poetry.dependencies]
bidict = "^0.21.4"
Flask = "^2.0.2"
connexion2 = { version = "^2.10.0", extras = ["swagger-ui"] }
flask-cors = "^3.0.8"
marshmallow = "^3.14.1"
marshmallow_enum = "^1.5.1"
tinydb = "^4.5.2"
python = "^3.10"
apscheduler = "^3.8.1"
multiprocessing_on_dill = "^3.5.0a4"
# Optional production web-server
cheroot = { version = "^8.5.2", optional = true }
requests = { version = "^2.26.0", optional = true }
# Optional image manipulation
Pillow = { version = "^8.4.0", optional = true }
# Optional PaperTTY e-ink controller
#papertty = { version = "^0.1.7", optional = true }
papertty = { git = "https://github.com/colin-nolan/PaperTTY.git", tag = "0.1.8", optional = true }  # Has updated dependencies to upstream

[tool.poetry.dev-dependencies]
Flask-Testing = "^0.8.1"
# Cannot be made optional on `webserver` extra: https://github.com/python-poetry/poetry/issues/129
get-port = "^0.0.5"
requests-toolbelt = "^0.9.1"

[tool.poetry.extras]
webserver = ["cheroot", "requests"]
image-tools = ["Pillow"]
papertty = ["papertty", "Pillow"]
localdisplay = ["Pillow"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 120
