[tool.poetry]
name = "remote_eink"
version = "0.0.1"
description = ""

license = "AGPLv3.0"

authors = [
    "Colin Nolan <cn580@alumni.york.ac.uk>"
]

readme = "README.md"
include = ["LICENSE", "openapi.yml"]

repository = ""
homepage = ""

keywords = []

[tool.poetry.dependencies]
bidict = "^0.19.0"
Flask = "^1.1.2"
connexion = { version = "^2.7.0", extras = ["swagger-ui"] }
flask-cors = "^3.0.8"
marshmallow = "^3.6.0"
marshmallow_enum = "^1.5.1"
tinydb = "^4.1.1"
python = "^3.8"
apscheduler = "^3.6.3"
multiprocessing_on_dill = "^3.5.0-alpha.4"

# Optional production web-server
cheroot = { version = "^8.3.0", optional = true }
requests = { version = "^2.23.0", optional = true }

# Optional image manipulation
Pillow = { version = "^7.1.2", optional = true }

# Optional PaperTTY e-ink controller
papertty = { version = "^0.1.3", optional = true }

[tool.poetry.dev-dependencies]
Flask-Testing = "^0.8.0"
# Cannot be made optional on `webserver` extra: https://github.com/python-poetry/poetry/issues/129
get-port = "^0.0.5"

[tool.poetry.extras]
webserver = ["cheroot", "requests"]
image-tools = ["Pillow"]
papertty = ["papertty", "Pillow"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
